enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
compression-level = 9  

[YouTube]
enabled = false
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" # fallback

[Music]
enabled = false
build-mode = "both"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "both"

[Music-Extended]
app-name = "Music"
patches-source = "mininxd/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[YouTube-Extended]
app-name = "YouTube"
patches-source = "mininxd/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Reddit-Extended]
enabled = false
build-mode = "apk"
patches-source = "ReVanced/revanced-patches"
integrations-source = "ReVanced/revanced-integrations"
cli-source = "ReVanced/revanced-cli"
rv-brand = "ReVanced"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
